stages:
  - test
  - build
  - deploy

run-tests:
  stage: test
  image: node:18-buster
  before_script:
    - apt-get update
    - apt-get -y install npm
    - npm install node 
  script: 
    - node test.js
  
build-image:
  stage: build
  image: docker:20.10.22
  services:
    - docker:20.10.22-dind
  variables: 
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker build -t nategoodman88/doewebscrapperapi:api-app-1.0 .
    - docker push nategoodman88/doewebscrapperapi:api-app-1.0 
  

